/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_ambari_servicemonitor_reporting_vsphere_VMGuestApi */

#ifndef _Included_org_apache_ambari_servicemonitor_reporting_vsphere_VMGuestApi
#define _Included_org_apache_ambari_servicemonitor_reporting_vsphere_VMGuestApi
#ifdef __cplusplus
extern "C" {
#endif
#undef org_apache_ambari_servicemonitor_reporting_vsphere_VMGuestApi_VMGUESTAPPMONITORLIB_ERROR_SUCCESS
#define org_apache_ambari_servicemonitor_reporting_vsphere_VMGuestApi_VMGUESTAPPMONITORLIB_ERROR_SUCCESS 0L
#undef org_apache_ambari_servicemonitor_reporting_vsphere_VMGuestApi_VMGUESTAPPMONITORLIB_ERROR_OTHER
#define org_apache_ambari_servicemonitor_reporting_vsphere_VMGuestApi_VMGUESTAPPMONITORLIB_ERROR_OTHER 1L
#undef org_apache_ambari_servicemonitor_reporting_vsphere_VMGuestApi_VMGUESTAPPMONITORLIB_ERROR_NOT_RUNNING_IN_VM
#define org_apache_ambari_servicemonitor_reporting_vsphere_VMGuestApi_VMGUESTAPPMONITORLIB_ERROR_NOT_RUNNING_IN_VM 2L
#undef org_apache_ambari_servicemonitor_reporting_vsphere_VMGuestApi_VMGUESTAPPMONITORLIB_ERROR_NOT_ENABLED
#define org_apache_ambari_servicemonitor_reporting_vsphere_VMGuestApi_VMGUESTAPPMONITORLIB_ERROR_NOT_ENABLED 3L
#undef org_apache_ambari_servicemonitor_reporting_vsphere_VMGuestApi_VMGUESTAPPMONITORLIB_ERROR_NOT_SUPPORTED
#define org_apache_ambari_servicemonitor_reporting_vsphere_VMGuestApi_VMGUESTAPPMONITORLIB_ERROR_NOT_SUPPORTED 4L
/*
 * Class:     org_apache_ambari_servicemonitor_reporting_vsphere_VMGuestApi
 * Method:    enable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_apache_ambari_servicemonitor_reporting_vsphere_VMGuestApi_enable
  (JNIEnv *, jobject);

/*
 * Class:     org_apache_ambari_servicemonitor_reporting_vsphere_VMGuestApi
 * Method:    disable
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_apache_ambari_servicemonitor_reporting_vsphere_VMGuestApi_disable
  (JNIEnv *, jobject);

/*
 * Class:     org_apache_ambari_servicemonitor_reporting_vsphere_VMGuestApi
 * Method:    isEnabled
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_apache_ambari_servicemonitor_reporting_vsphere_VMGuestApi_isEnabled
  (JNIEnv *, jobject);

/*
 * Class:     org_apache_ambari_servicemonitor_reporting_vsphere_VMGuestApi
 * Method:    markActive
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_apache_ambari_servicemonitor_reporting_vsphere_VMGuestApi_markActive
  (JNIEnv *, jobject);

/*
 * Class:     org_apache_ambari_servicemonitor_reporting_vsphere_VMGuestApi
 * Method:    getAppStatus
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_apache_ambari_servicemonitor_reporting_vsphere_VMGuestApi_getAppStatus
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
